# Site settings
title: Ivan
name: Ivan's Blog
email: yanziily@gmail.com
description: 'Ivan&#039;s Blog'
keywords: 'Ivan,秋叶随风,blog,Android,kernel,linux,ROM,CyanogenMod,Xiaomi,MIUI'
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.3rdos.com" # the base hostname & protocol for your site
github: ivan19871002

author:
  name: Ivan
  email: yanziily@gmail.com
  github: ivan19871002
  bio: 'Ivan&#039;s Blog'


# Build settings
paginate: 10
paginate_path: "page/:num/"
highlighter: pygments
markdown: kramdown
rss_path: feed
categories_path: categories.html
tags_path: tags.html
